-- Initial schema for Recallr application
-- Created based on JPA entities

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    share_token VARCHAR(64) UNIQUE
);

-- Tags table
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_tags_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Contents table
CREATE TABLE contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048),
    embed_url VARCHAR(2048),
    title VARCHAR(512),
    thumbnail_url VARCHAR(2048),
    type VARCHAR(32) NOT NULL,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_contents_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Content-Tags join table
CREATE TABLE content_tags (
    content_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (content_id, tag_id),
    CONSTRAINT fk_content_tags_content FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE,
    CONSTRAINT fk_content_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- Refresh tokens table
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes for better performance
CREATE INDEX idx_tags_user_id ON tags(user_id);
CREATE INDEX idx_contents_user_id ON contents(user_id);
CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id);