-- pgvector-backed storage for Recallr RAG chunks.
-- Gemini embedding-001 supports flexible dimensions up to 3072; this schema stores 768-dimensional vectors.
-- Keep Gemini's output_dimensionality set to 768 in the embedding client.

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE contents
    ADD COLUMN processing_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';

CREATE TABLE content_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    text TEXT NOT NULL,
    token_estimate INTEGER,
    metadata_json JSONB,
    embedding vector(768) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_content_chunks_content FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE,
    CONSTRAINT fk_content_chunks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_content_chunks_content_index UNIQUE (content_id, chunk_index)
);

CREATE INDEX idx_contents_user_processing_status ON contents(user_id, processing_status);
CREATE INDEX idx_content_chunks_content_id ON content_chunks(content_id);
CREATE INDEX idx_content_chunks_user_id ON content_chunks(user_id);
CREATE INDEX idx_content_chunks_embedding_hnsw
    ON content_chunks
    USING hnsw (embedding vector_cosine_ops);
