CREATE TABLE extracted_documents
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id    BIGINT      NOT NULL,
    source_kind   VARCHAR(32) NOT NULL,
    raw_text      TEXT,
    metadata_json JSONB,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_extracted_documents_content
        FOREIGN KEY (content_id) REFERENCES contents (id) ON DELETE CASCADE
);

CREATE INDEX idx_extracted_documents_content_id ON extracted_documents (content_id);